
services:
  sftp:
    image: atmoz/sftp
    container_name: local_sftp_server
    ports:
      - "2222:22"
    volumes:
      - ./data:/home/${SFTP_USER}/upload
    environment:
      - SFTP_USERS=${SFTP_USER}:${SFTP_PASSWORD}:1001
    restart: unless-stopped
